dist: focal

addons:
  apt:
    packages:
      - libboost-dev
      - clang-12

env:
 - CC=clang CXX=clang++-12 STD=14
 - CC=gcc CXX=g++ STD=14
 - CC=clang CXX=clang++-12 STD=17
 - CC=gcc CXX=g++ STD=17

script:
 - cmake -DCMAKE_CXX_STANDARD=$STD .
 - make
 - make test

